config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmations: 'users/confirmations'}
  root to: "pages#home"
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  resources :loads, only: [:show, :index, :new, :create, :edit, :update]
  resources :trucks, only: [:show, :index, :new, :create, :edit, :update]
  get "profile", to: "pages#profile"
  get "all_trucks", to: "pages#all_trucks"
  get "all_loads", to: "pages#all_loads"
  get '/truck_templates', to: 'trucks#truck_templates'
  get '/load_templates', to: 'loads#load_templates'
  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"
  patch '/trucks/:id/change_status', to: 'trucks#change_status', as: 'change_truck_status'
  patch '/loads/:id/change_status', to: 'loads#change_status', as: 'change_load_status'
end

app/views/shared/_change_parameters.html.erb
<div class="bg-white rounded-sm pt-4 pb-3 px-4 mb-3 shadow-sm">
  <p class="text-center">Нема ниеден товар што одговара на вашето возило.</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="bg-info text-center text-primary py-3" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="bg-warning text-center text-danger py-3" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_home_tabs.html.erb
<div class="d-flex">
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(trucks_path) %> border-primary
    <% end %>">
    <%= link_to "Товар", trucks_path %>
  </p>
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(loads_path) %> border-primary
    <% end %>">
    <%= link_to "Возило", loads_path %>
  </p>
</div>

app/views/shared/_index_tabs.html.erb
<div class="d-flex">
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(trucks_path) %> border-primary
    <% end %>">
    <%= link_to "Товар", trucks_path %>
  </p>
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(loads_path) %> border-primary
    <% end %>">
    <%= link_to "Возило", loads_path %>
  </p>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_my_post.html.erb
<div class="bg-white pt-4 pb-3 px-4 mb-3 shadow-sm" style="border-radius: 1rem;">
  <div class="d-flex justify-content-between align-items-center">
    <% if t.status? %>
    <p class="tag-pill-status fw-bold text-black bg-info border border-primary border-1"><small>АКТИВНО</small></p>
    <% else %>
    <p class="tag-pill-status fw-bold text-black bg-warning border border-danger border-1"><small>НЕАКТИВНО</small></p>
    <% end %>
    <p class="text-muted text-end"><small><%= t.ago %></small></p>
  </div>
  <div class="d-flex justify-content-between">
    <div class="d-flex text-truncate" style="width: 50%">
      <p class="m-0"><%= image_tag "countries/#{t.pickup.country}.svg", style: "width: 1.15rem; border-radius: 2rem; margin-bottom: 0.15rem; margin-right: 0.3rem;" %></p>
      <p class="my-0 text-truncate"><%= t.pickup.simple %></p>
    </div>
    <div class="d-flex justify-content-end text-truncate" style="width: 50%">
      <p class="m-0 text-end text-truncate"><%= t.dropoff.simple %></p>
      <p class="m-0"><%= image_tag "countries/#{t.dropoff.country}.svg", style: "width: 1.15rem; border-radius: 1rem; margin-bottom: 0.15rem; margin-left: 0.3rem;" %></p>
    </div>
  </div>
  <div class="d-flex flex-wrap mt-3">
  <p class="tag-pill"><small><%= t.loading_date.try(:strftime, ("%b %e, %a")) %></small></p>
  <% t.truck_type.drop(1).each do |truck| %>
    <p class="tag-pill"><small><%= truck %></small></p>
  <% end %>
  <p class="tag-pill"><small><%= t.length %><%= "m" %></small></p>
  <% if t.weight.present? %>
  <p class="tag-pill"><small><%= t.weight.to_i %><%= "t" %></small></p>
  <% end %>
  </div>
</div>

app/views/shared/_my_post_show.html.erb
<div class="px-3 border <%= @truck.status? ? "border-info" : "" %> border-2 pt-3 pb-3 mb-3" style="border-radius: 0.75rem;">
  <div class="d-flex px-1 justify-content-between">
    <div class="d-flex text-truncate" style="width: 50%">
      <p class="m-0"><%= image_tag "countries/#{@truck.pickup.country}.svg", style: "width: 1.15rem; border-radius: 2rem; margin-bottom: 0.15rem; margin-right: 0.3rem;" %></p>
      <p class="my-0 fw-bolder text-truncate"><%= @truck.pickup.simple %></p>
    </div>
    <div class="d-flex justify-content-end text-truncate" style="width: 50%">
      <p class="m-0 text-end fw-bolder text-truncate"><%= @truck.dropoff.simple %></p>
      <p class="m-0"><%= image_tag "countries/#{@truck.dropoff.country}.svg", style: "width: 1.15rem; border-radius: 1rem; margin-bottom: 0.15rem; margin-left: 0.3rem;" %></p>
    </div>
  </div>

  <p class="mt-2 px-1 text-muted mb-0"><small>
    <%= @truck.loading_date.try(:strftime, ("%b %e")) %>;
    <% @truck.truck_type.drop(1).each do |truck| %>
      <%= truck %>;
    <% end %>
    <%= @truck.length %> m;
    <% if @truck.weight? %>
      <%= @truck.weight.to_i %> t;
    <% end %>
  </small></p>

  <% if policy(@truck).edit? %>
    <% if @truck.status? %>
      <div class="row mt-2 g-2">
        <div class="col-lg-4">
          <% if @truck.type == "Load" %>
          <%= link_to edit_load_path, "data-turbo" => "false", class: "btn btn-sm bg-info border-0 text-truncate btn-outline-primary w-100", style: "border-radius: 0.25rem;" do %>
            <i class="fa fa-solid fa-pen text-primary"></i> Измени филтри
          <% end %>
          <% else %>
          <%= link_to edit_truck_path, "data-turbo" => "false", class: "btn btn-sm bg-info border-0 text-truncate btn-outline-primary w-100", style: "border-radius: 0.25rem;" do %>
            <i class="fa fa-solid fa-pen text-primary"></i> Измени филтри
          <% end %>
          <% end %>
        </div>
        <div class="col-lg-4">
          <%= mail_to("",
            :subject => "#{@truck.type == "Load" ? "Барам камион" : "Барам товар"}",
            :body => "Здраво!\r\n\r\nБарам #{@truck.type == "Truck" ? "товар" : "камион" } од #{@truck.pickup.simple} до #{@truck.dropoff.simple}.\r\n\r\nПовеќе детали најдете овде 👇🏻\r\n\r\n#{request.original_url}\r\n\r\nПоздрав,\r\n\r\n#{current_user.first_name}\r\n\r\nОвој мејл го генерирав автоматски преку Cargster.co",
            class: "btn btn-sm bg-info border-0 btn-outline-primary text-truncate w-100", style: "border-radius: 0.25rem;") do
          %>
            <i class="fa fa-solid fa-envelope text-primary"></i> Сподели по е-пошта
          <% end %>
        </div>
        <div class="col-lg-4">
          <% if @truck.type == "Load" %>
          <%= link_to change_load_status_path(@truck), data: { turbo_confirm: 'Оваа акција не можете да ја вратите. Дали сте сигурни?', turbo_method: :patch }, class:"btn btn-sm bg-warning text-danger border-0 btn-danger text-truncate w-100", style: "border-radius: 0.25rem;" do %>
            <i class="fa fa-solid fa-times text-danger"></i> Деактивирај
          <% end %>
          <% else %>
          <%= link_to change_truck_status_path(@truck), data: { turbo_confirm: 'Оваа акција не можете да ја вратите. Дали сте сигурни?', turbo_method: :patch }, class:"btn btn-sm bg-warning text-danger border-0 btn-danger text-truncate w-100", style: "border-radius: 0.25rem;" do %>
            <i class="fa fa-solid fa-times text-danger"></i> Деактивирај
          <% end %>
          <% end %>
        </div>
      </div>
    <% else %>
      <%= render 'shared/post_inactive' %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="col-lg-9 mx-auto mb-2 rounded-3 sticky-top px-4 pt-4 pb-3" style="background-color: #F4F4F4">
  <div class="d-flex justify-content-between align-items-center">
    <%= link_to root_path do %>
      <%= image_tag "logo_zoom.png", style: "width: 2rem; border-radius: 0.5rem;", class: "" %>
    <% end %>

    <p class="fw-bolder m-0"><%= @page_name ||
      if current_page?(new_user_session_path)
        "Најави се"
      elsif current_page?(new_user_registration_path)
        "Регистрација"
      elsif current_page?(new_user_password_path)
        "Заборавена лозинка"
      elsif current_page?(edit_user_registration_path)
        "Подесувања"
      end
    %></p>
    <% if current_page?(new_truck_path) %>
      <%= link_to truck_templates_path, class:"text-primary" do %>
        <i class="fa fa-solid fa-lg fa-clock-rotate-left"></i>
      <% end %>
    <% elsif current_page?(new_load_path) %>
      <%= link_to load_templates_path, class:"text-primary" do %>
        <i class="fa fa-solid fa-lg fa-clock-rotate-left"></i>
      <% end %>
    <% else %>
    <div class="nav-item dropdown">
      <i type="button" class="fa fa-solid fa-bars fa-lg text-primary" data-bs-toggle="dropdown" aria-expanded="false">
      </i>
      <div class="dropdown-menu dropdown-menu-end shadow-lg" aria-labelledby="navbarDropdown">
        <%= link_to root_path, class: "dropdown-item" do %>
          <i class="fa fa-solid fa-list"></i> Денешни објави
        <% end %>
        <hr class="dropdown-divider">
        <%= link_to trucks_path, class: "dropdown-item" do %>
          <i class="fa fa-solid fa-magnifying-glass"></i> Мои барања
        <% end %>
        <hr class="dropdown-divider">
        <%= link_to  truck_templates_path, class: "dropdown-item" do %>
          <i class="fa fa-solid fa-clock-rotate-left"></i> Шаблони
        <% end %>
        <hr class="dropdown-divider">
        <%= link_to profile_path, class: "dropdown-item" do %>
          <i class="fa fa-solid fa-user"></i> Профил
        <% end %>
        <hr class="dropdown-divider">
        <%= mail_to '',
          subject: 'Придружете ми се како ран корисник на Cargster.co',
          body: "Здраво!\r\n\r\nСакав да ве известам за Cargster.co, нова платформа која го поедноставува процесот на размена на товар.\r\n\r\nКако професионалец во индустријата, мислам дека оваа апликација ќе биде вредна алатка за подобрување на комуникацијата и ефикасноста во индустријата.\r\n\r\nМожете да се регистрирате за Cargster.co бесплатно користејќи ја оваа врска:\r\n\r\nhttps://www.cargster.co/users/sign_up\r\n\r\nПоздрав.",
          class:"dropdown-item" do
        %>
          <i class="fa fa-solid fa-paper-plane"></i> Покани корисник
        <% end %>
        <hr class="dropdown-divider">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" do %>
          <i class="fa fa-solid fa-right-from-bracket"></i> Одјави се
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_new_post.html.erb
<div class="container px-4 mt-1 mb-5">
  <%= simple_form_for @post do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification alert: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="row">
      <div class="col-lg-6">
      <%= f.input :loading_date, placeholder: "Loading date", html5: true, label: "Датум на утовар", input_html: {class: "picker", min: "#{Date.today}"} %>

      <%= f.input :truck_type, label: "Тип на возило", as: :check_boxes, input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item', collection: [ "Церада", "Мега", "Хладнњача", "Цистерна", "Комбе", "Тандем", "АДР", "Камион(под 7.5т)" ] %>
      <div class="row">
        <div class="col-6 n-top">
          <%= f.input :length, label: "Должина", placeholder: "Метри", input_html: { type: 'number', pattern: '\d+(\,\d+)?' } %>
        </div>
        <div class="col-6 n-top">
          <%= f.input :weight, label: "Тежина", placeholder: "Тони" %>
        </div>
      </div>
        <script>
          addEventListener("load", () => {
            var suggestionLists = document.getElementsByClassName("suggestions");
            setTimeout(() => {
              for (var i = 0; i < suggestionLists.length; i++) {
                suggestionLists[i].style.display = "none"
            }
            }, 1000);
          });
        </script>
      </div>
      <div class="col-lg-6">
      <%= f.simple_fields_for :pickup, @post.pickup do |build| %>
        <%= build.input :place, label: "Преферирано место на утовар",
          input_html: {data: {address_autocomplete_target: "address"}, class:"d-none", },
          wrapper_html: {data: {controller: "address-autocomplete",
          address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
      <% end %>

      <%= f.simple_fields_for :dropoff, @post.dropoff do |build| %>
        <%= build.input :place, label: "Преферирано место на истовар",
          input_html: {data: {address_autocomplete_target: "address"}, class:"d-none"},
          wrapper_html: {data: {controller: "address-autocomplete",
          address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
      <% end %>
    <%= f.input :comment, label:"Коментар", id: "textarea", placeholder: "Пр: Цена, Бр. камион, Референтен број или слично" %>
    </div>
    </div>
    <%= f.submit 'Барај', class: " mt-2 btn btn-primary w-100 text-white" %>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="bg-white pt-4 pb-3 px-4 mb-3 shadow-sm" style="border-radius: 1rem;">
  <div class="d-flex justify-content-between align-items-center">
    <p class="text-truncate fw-bold"><%= t.user.first_name %> <%= t.user.last_name[0] %>.</p>
    <p class="text-muted text-end text-nowrap"><small><%= t.ago %></small></p>
  </div>
  <div class="d-flex justify-content-between">
    <div class="d-flex text-truncate" style="width: 50%">
      <p class="m-0"><%= image_tag "countries/#{t.pickup.country}.svg", style: "width: 1.15rem; border-radius: 2rem; margin-bottom: 0.15rem; margin-right: 0.3rem;" %></p>
      <p class="my-0 text-truncate"><%= t.pickup.simple %></p>
    </div>
    <div class="d-flex justify-content-end text-truncate" style="width: 50%">
      <p class="m-0 text-end text-truncate"><%= t.dropoff.simple %></p>
      <p class="m-0"><%= image_tag "countries/#{t.dropoff.country}.svg", style: "width: 1.15rem; border-radius: 1rem; margin-bottom: 0.15rem; margin-left: 0.3rem;" %></p>
    </div>
  </div>
  <div class="d-flex flex-wrap mt-3">
  <p class="tag-pill"><small><%= t.loading_date.try(:strftime, ("%b %e, %a")) %></small></p>
  <% t.truck_type.drop(1).each do |truck| %>
    <p class="tag-pill"><small><%= truck %></small></p>
  <% end %>
  <p class="tag-pill"><small><%= t.length %><%= "m" %></small></p>
    <% if t.weight? %>
  <p class="tag-pill"><small><%= t.weight %><%= "t" %></small></p>
  <% end %>
  </div>
</div>

app/views/shared/_post_inactive.html.erb
<% if @truck.type == "Truck" %>
  <%= link_to "Активирај", new_truck_path(
    :truck_type => @truck.truck_type,
    :length => @truck.length,
    :weight => @truck.weight,
    :comment => @truck.comment,
    :pickup => @truck.pickup.place,
    :dropoff => @truck.dropoff.place
  ), "data-turbo" => "false",
  class: "btn btn-sm text-primary bg-info mt-3 w-100", style: "border-radius: 0.5rem;" %>
<% else %>
  <%= link_to "Активирај", new_load_path(
    :truck_type => @truck.truck_type,
    :length => @truck.length,
    :weight => @truck.weight,
    :comment => @truck.comment,
    :pickup => @truck.pickup.place,
    :dropoff => @truck.dropoff.place
  ), "data-turbo" => "false",
  class: "btn btn-sm text-primary bg-info mt-3 w-100", style: "border-radius: 0.5rem;" %>
<% end %>

app/views/shared/_post_template.html.erb
<div class="bg-white pt-4 pb-3 px-4 mb-3 shadow-sm" style="border-radius: 1rem;">
  <div class="d-flex justify-content-between">
    <div class="d-flex text-truncate" style="width: 50%">
      <p class="m-0"><%= image_tag "countries/#{t.pickup.country}.svg", style: "width: 1.15rem; border-radius: 2rem; margin-bottom: 0.15rem; margin-right: 0.3rem;" %></p>
      <p class="my-0 text-truncate"><%= t.pickup.simple %></p>
    </div>
    <div class="d-flex justify-content-end text-truncate" style="width: 50%">
      <p class="m-0 text-end text-truncate"><%= t.dropoff.simple %></p>
      <p class="m-0"><%= image_tag "countries/#{t.dropoff.country}.svg", style: "width: 1.15rem; border-radius: 1rem; margin-bottom: 0.15rem; margin-left: 0.3rem;" %></p>
    </div>
  </div>
  <div class="d-flex flex-wrap mt-3">
  <% t.truck_type.drop(1).each do |truck| %>
    <p class="tag-pill"><small><%= truck %></small></p>
  <% end %>
  <p class="tag-pill"><small><%= t.length %><%= "m" %></small></p>
  <% if t.weight? %>
  <p class="tag-pill"><small><%= t.weight %><%= "t" %></small></p>
  <% end %>
  </div>
</div>

app/views/shared/_prefilled_email.html.erb
<%= mail_to '', 'Прати покани',
  subject: 'Придружете ми се како ран корисник на Cargster.co',
  body: "Здраво!\r\n\r\nСакав да ве известам за Cargster.co, нова платформа која го поедноставува процесот на размена на товар.\r\n\r\nКако професионалец во индустријата, мислам дека оваа апликација ќе биде вредна алатка за подобрување на комуникацијата и ефикасноста во индустријата.\r\n\r\nМожете да се регистрирате за Cargster.co бесплатно користејќи ја оваа врска:\r\n\r\nhttps://www.cargster.co/users/sign_up\r\n\r\nПоздрав.",
  class:"btn btn-primary text-white w-100"
%>

app/views/shared/_templates_tabs.html.erb
<div class="d-flex">
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(truck_templates_path) %> border-primary
    <% end %>">
    <%= link_to "Товар", truck_templates_path %>
  </p>
  <p class="text-center text-truncate pb-3 w-50 border-bottom border-3
    <% if current_page?(load_templates_path) %> border-primary
    <% end %>">
    <%= link_to "Возило", load_templates_path %>
  </p>
</div>