config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmations: 'users/confirmations'}
  root to: "pages#home"
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  resources :loads, only: [:show, :index, :new, :create, :edit, :update]
  resources :trucks, only: [:show, :index, :new, :create, :edit, :update]
  get "profile", to: "pages#profile"
  get "all_trucks", to: "pages#all_trucks"
  get "all_loads", to: "pages#all_loads"
  get '/truck_templates', to: 'trucks#truck_templates'
  get '/load_templates', to: 'loads#load_templates'
  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"
  patch '/trucks/:id/change_status', to: 'trucks#change_status', as: 'change_truck_status'
  patch '/loads/:id/change_status', to: 'loads#change_status', as: 'change_load_status'
end

app/views/pages/all_loads.html.erb
<div class="px-3 col-lg-9 mx-auto">
  <%= render 'shared/home_tabs' %>
  <% if !current_user.profile_complete? %>
    <%= render 'shared/messages/complete_profile' %>
  <% else %>
    <%= link_to new_truck_path do %>
      <p class="w-100 btn mb-3 text-white btn-primary"><i class="fa fa-solid fa-search"></i> Филтрирај</p>
    <% end %>
    <% if @loads.length != 0 %>
      <% @loads.each do |t| %>
        <%= link_to load_path(t) do %>
          <%= render 'shared/post', t: t %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= will_paginate @loads, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/pages/all_trucks.html.erb
<div class="px-3 col-lg-9 mx-auto">
  <%= render 'shared/home_tabs' %>
  <% if !current_user.profile_complete? %>
    <%= render 'shared/messages/complete_profile' %>
  <% else %>
    <%= link_to new_load_path do %>
      <p class="w-100 btn mb-3 text-white btn-primary"><i class="fa fa-solid fa-search"></i> Филтрирај</p>
    <% end %>
    <% @trucks.each do |t| %>
      <%= link_to truck_path(t) do %>
        <%= render 'shared/post', t: t %>
      <% end %>
    <% end %>
  <% end %>
  <%= will_paginate @trucks, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/pages/home.html.erb
<%= render 'shared/value_proposition' %>

app/views/pages/privacy.erb
<div class="p-4 col-lg-6 mx-auto">
    <h4>Политика за приватност на нашата веб-апликација:</h4>

    <p>Ние сме посветени на заштита на приватноста на нашите корисници и ја имплементиравме оваа политика за приватност за да обезбедиме транспарентност и да обезбедиме усогласеност со важечките закони.</p>
    <p>Ние собираме и обработуваме лични информации како што се вашето име, адреса на е-пошта, телефонски број, име на компанија, целосна адреса, даночен број на субјект, матичен број на субјект и IP адреса кога се регистрирате за сметка и ја користите нашата услуга.</p>
    <p>Ние ги користиме личните информации за да ја обезбедиме услугата, како што се креирање и усогласување објави, и за внатрешни цели како што се аналитика и подобрување на услугата.</p>
    <p>Можеме да споделиме лични информации со трети лица даватели на услуги заради обезбедување на услугата, како што се хостирање и одржување.</p>
    <p>Ние не користиме колачиња, немаме врски до надворешни веб-локации.</p>
    <p>Преземаме соодветни мерки за заштита на личните информации од неовластен пристап, промена, откривање или уништување.</p>
    <p>Со користење на нашата услуга, вие се согласувате за собирање, користење и споделување на вашите лични информации како што е опишано во оваа политика.</p>
    <p>Имате право да барате пристап до вашите лични информации, да побарате корекција или бришење на вашите лични информации и да се спротивставите на обработката на вашите лични информации.</p>
    <p>Го задржуваме правото да ја измениме оваа политика за приватност во секое време и ќе обезбедиме известување за какви било материјални промени.</p>
  <div class=" p-4 text-center">
    <small>
    <%= mail_to "nikola@cargster.co", "Контакт" %>
    -
    <%= link_to "Пoлитика на приватност", privacy_path %>
    -
    <%= link_to "Услови на користење", terms_path %>
    <p class="my-2">© Cargster 2023</p>
    </small>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="col-lg-9 mx-auto px-4">
  <%= render 'shared/messages/complete_profile' if current_user.blank_attributes? %>
  <% if current_user.profile_complete? %>
  <div class="d-lg-flex w-100">
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="text-center fa fa-solid fa-user text-primary"></span></p>
      <p class="mx-3"><%= @user.first_name %> <%= @user.last_name %></p>
    </div>
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="text-center fa fa-solid fa-building text-primary"></span></p>
      <p class="mx-3"><%= @user.company %></p>
    </div>
    <% end %>
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="text-center fa fa-solid fa-envelope text-primary"></span></p>
      <p class="mx-3"><%= @user.email %></p>
    </div>
    <% if current_user.profile_complete? %>
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="text-center fa fa-solid fa-phone text-primary"></span></p>
      <p class="mx-3"><%= @user.phone_number %></p>
    </div>
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="mx-1 text-center fa fa-solid fa-location-arrow text-primary"></span></p>
      <p class="mx-3"><%= @user.address %></p>
    </div>
    <div class="d-flex">
      <p class="text-center" style="width: 1.5rem;"><span class="mx-1 text-center fa fa-solid fa-book text-primary"></span></p>
      <p class="mx-3"><%= @user.coc %> (MБ) <br> <%= @user.vat %> (ДБ)</p>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/terms.erb
<div class="p-4 col-lg-6 mx-auto">
  <h4>Услови за користење на нашата веб-апликација:</h4>
  <p>Со регистрирање за сметка на нашата веб-апликација, потврдувате дека сте ги
   прочитале и се согласувате со овие услови за користење.</p>
  <p>Нашата веб-апликација првично е обезбедена бесплатно, но го задржуваме правото
   да ја монетизираме во иднина, во тој случај ќе ги известиме нашите корисници и ќе
    обезбедиме опција корисникот да прекине со користење на услугата.</p>
  <p>Вие сте единствено одговорни за обезбедување точни и целосни информации при
   пополнување на вашиот профил, вклучувајќи го вашето полно име, име на компанија,
   мобилен број, целосна адреса на компанијата, ДДВ и број на стопанска комора.
   </p>
  <p>Може да креирате објави за камион или товар со внесување на бараните
  информации, како што се датумот на товарење, типот на возилото, регионите за
  утовар и истовар, должина и тежина. Достапни се и изборни полиња, како што се
   дополнителни коментари.</p>
  <p>Може да гледате други објави, вклучувајќи ги информациите
  за објавата и корисникот кој го објавил.</p>
  <p>Може да контактирате со други корисници преку е-пошта, Viber, WhatsApp или да
  се јавите.</p>
  <p>Можете да ги деактивирате вашите сопствени објави во секое време.</p>
  <p>Го задржуваме правото да отстраниме која било содржина или да укинеме сметки
   што ги прекршуваат нашите услови за користење или важечките закони.</p>
  <p>Нашата веб-апликација е обезбедена на основа „како што е“ и „како што е
  достапна“ и не даваме гаранција дека ќе ги исполни вашите барања или ќе биде
  достапна на непрекината, безбедна или без грешки основа.</p>
  <p>Со користење на услугата, вие се согласувате да не држите безопасни
  од какви било побарувања, штети, загуби или трошоци кои
  произлегуваат од или на кој било начин поврзани со вашата употреба на услугата.</p>
  <p>Го задржуваме правото да ги измениме овие услови за користење во секое
  време и ќе обезбедиме известување за какви било промени.</p>
  <div class=" p-4 text-center">
    <small>
    <%= mail_to "nikola@cargster.co", "Контакт" %>
    -
    <%= link_to "Пoлитика на приватност", privacy_path %>
    -
    <%= link_to "Услови на користење", terms_path %>
    <p class="my-2">© Cargster 2023</p>
    </small>
  </div>
</div>